filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/siem-sandbox/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: false
    ignore_older: 72h
    fields:
      service.name: siem-sandbox
      event.dataset: sandbox.logs
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

logging.level: info
logging.to_files: false
logging.to_stderr: true
