auditbeat.modules:
  - module: system
    datasets:
      - host
      - user
      - login
      - process
    period: 10s

  - module: file_integrity
    paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

setup.template.enabled: true
setup.template.name: "auditbeat"
setup.template.pattern: "auditbeat-*"

logging.level: info
logging.to_files: false
logging.to_stderr: true
